export const DRIVER_POSITIONS = ["Car Driver", "Motorcycle Driver"];
export const USER_ROLES = ["Admin", "Manager", "Employee", "Accountant"];
export const USER_POSITIONS = [
  "Administrative",
  "Engineer",
  "Accountant",
  "Representative",
  "MarketingManager",
  "SalesManager",
  "HRManager",
  "ProjectManager",
  "ProductManager",
  "BusinessAnalyst",
  "SoftwareEngineer",
  "WebDeveloper",
  "GraphicDesigner",
  "ContentWriter",
  "CustomerSupportRepresentative",
  "DataAnalyst",
  "OperationsManager",
  "AdminAssistant",
  "TeamLeader",
  "MarketingSpecialist",
  "LegalAdvisor",
  "ITSupportSpecialist",
  "Receptionist",
  "Intern",
  "MarketingSpecialist",
  "LegalAdvisor",
  "ITSupportSpecialist",
  "Receptionist",
  "Intern",
  "Representative",
  "Administrative",
  "Engineer",
  "Accountant",
];
export const BANK_NAMES = [
  "National Bank of Kuwait (NBK)",
  "Kuwait Finance House (KFH)",
  "Burgan Bank",
  "Gulf Bank",
  "Commercial Bank of Kuwait",
  "Al Ahli Bank of Kuwait",
  "Boubyan Bank",
  "Kuwait International Bank",
  "Warba Bank",
  "Industrial Bank of Kuwait",
];
